name = "samui-landing"
compatibility_date = "2025-10-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "samui"
database_id = "10380cee-10bb-456c-a447-a0d547d9bd05"
